### ISSUE TITLE
missing examples

### ISSUE THREAD

**Issue by staabm** [hitmeister/api-sdk-php#1]
do you have somewhere examples on how to use the api to e.g. retrieve orders?

atm I only have a REST based documentation which I can use to build my own client but at least some information on how to use this sdk would be very helpfull.

did I miss it somewhere?

**Comment by digitalcrab** [comment]
Right now we don't have a detailed documentation. And we are working on it. But the source is documented a little bit and you can easely find the way hot the get orders. 

For example:

```php
require 'vendor/autoload.php';

use Hitmeister\Component\Api\ClientBuilder;

$client = ClientBuilder::create()
    ->setClientKey('YOUR_CLIENT_KEY')
    ->setClientSecret('YOUR_CLIENT_SECRET')
    ->build();

        foreach ($client->orderUnits()->find() as $orderUnit) {
            echo $orderUnit->buyer->email;
            echo $orderUnit->id_offer;
            echo $orderUnit->shipping_address->street;
            echo $orderUnit->shipping_address->house_number;
            echo $orderUnit->shipping_address->city;
            echo $orderUnit->shipping_address->country;
            echo $orderUnit->shipping_address->phone;
        }
```

**Comment by trailsnail** [comment]
This works, nice.
But now we have another question: we received the buyers pseudonym, firstname and last-name via the old api. In the new version we have only the "id_buyer" and  email. How can we the needed information?

**Comment by digitalcrab** [comment]
Hello
Please take a look on [Retrieving Orders](https://www.hitmeister.de/api/v1/?page=orders#retrieving-orders) section. You can get the orders with the `shipping_address ` and `billing_address` embedded fileds. There you can find the `first_name`, `last_name` and `company_name`.

For example: `echo $orderUnit->shipping_address->first_name;` - same as an example above.

**Comment by digitalcrab** [comment]
Regarding payment state. All the orders are paid. So, you don't have to worry about the state of it.

**Comment by trailsnail** [comment]
Ok - thanks. We thought the buyer could be another person, than the billing- or delivery-person. But in this case I use the billing-fields
