### ISSUE TITLE
ticket-messages error

### ISSUE THREAD

**Issue by juansiwei-li** [hitmeister/api-sdk-php#100]
post success return {"message": "Internal server error"}

**Comment by juansiwei-li** [comment]
post success but return {"message": "Internal server error"}

**Comment by NastiaNovik** [comment]
Hey @juansiwei-li! Could you please give more info? Like example of your request and if you want me to check our logs of your requests you can also send me id or name of your shop to email anastasiia.novik@real-digital.de.

**Comment by NastiaNovik** [comment]
@juansiwei-li I think the problem occurred  due to the temporary internal outage we had this morning. It should be fine again;)

**Comment by juansiwei-li** [comment]
Hello we will try again
