### ISSUE TITLE
signature error

### ISSUE THREAD

**Issue by HANK1998** [hitmeister/api-sdk-php#109]
`<?php

      $method = "PATCH";
      $uri = "https://www.kaufland.de/api/v1/order-units/XXXXXXXXXXXX/send/";
      $body = null;
      $timestamp = time(); //time();
      $secretKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
      
      $hmac = signRequest($method, $uri, $body, $timestamp, $secretKey);
      print("\n$hmac\n"); 
      
      function signRequest($method, $uri, $body, $timestamp, $secretKey)
      {
	      $string = implode("\n", [
		      $method,
		      $uri,
		      $body,
		      $timestamp,
	      ]);
      
	      return hash_hmac('sha256', $string, $secretKey);
      }`

Hello, I use the API documentation to provide the sample code generated by the signature, and then initiate the request, always prompt signature error, I according to the requirements of the API format to fill in and launch a request, hope to know what causes, thanks

GET method is succeed,POST and PATCH method is Failed.

**Comment by NastiaNovik** [comment]
@HANK1998 I think you are missing part of the request, you also need to provide a **$clientKey** to get some data back. In the documentation you mention it is done in the header:

> $headers = [
>     'Accept: application/json',
>     'Hm-Client: ' . $clientKey,
>     'Hm-Timestamp: ' . $timestamp,
>     'Hm-Signature: ' . signRequest('POST', $uri, $jsonData, $timestamp, $secretKey),
> ];

Please take a look at [readme file](https://github.com/hitmeister/api-sdk-php#readme) to connect to the API in the simple way.

**Comment by HANK1998** [comment]
> 
> 
> @HANK1998 I think you are missing part of the request, you also need to provide a **$clientKey** to get some data back. In the documentation you mention it is done in the header:
> 
> > $headers = [
> > 'Accept: application/json',
> > 'Hm-Client: ' . $clientKey,
> > 'Hm-Timestamp: ' . $timestamp,
> > 'Hm-Signature: ' . signRequest('POST', $uri, $jsonData, $timestamp, $secretKey),
> > ];
> 
> Please take a look at [readme file](https://github.com/hitmeister/api-sdk-php#readme) to connect to the API in the simple way.

Thank you. The problem lies in the method of generating signature. I think I have found the answer. The parameter body cannot be empty. I misunderstood the sample code in the document. Thank you for your help.
