### ISSUE TITLE
FR: Reduce flooding of error messages

### ISSUE THREAD

**Issue by polluks** [hitmeister/api-sdk-php#112]
````
Fehler beim Datei-Upload
Hallo Herr ***, 
die von Ihnen hochgeladene Datei konnte nicht verarbeitet werden. 
Die Fehlermeldung lautet: DOWNLOADING_FAILED 
````
https://github.com/hitmeister/api-sdk-php/blob/d6fb2afef89bea4817aa5968b73c9bb590cbc534/src/Transfers/Constants.php#L85

**Comment by NastiaNovik** [comment]
Hi @polluks, could you please explain a bit more about your request?

**Comment by polluks** [comment]
I suppose notification is not the job of your sdk. However, Kaufland.de is sending this message every (!) hour :-(
Do you have any cure?

**Comment by NastiaNovik** [comment]
@polluks what kind of notification? Where do you get it? If it is not connected to SDK, maybe you want to contact me directly? My email is anastasiia.novik@real-digital.de

**Comment by polluks** [comment]
It was triggered at https://www.kaufland.de/seller/automatic-product-data-file-upload/.
