### ISSUE TITLE
I can't create new product,can you help me

### ISSUE THREAD

**Issue by fengmiq** [hitmeister/api-sdk-php#113]
Since July 1, I have been using API to upload products and have been reporting errors. can you help me! I use "PUT /product-data/{ean}" add new product,return errr:
`{
  "item_ready": false,
  "update_status": "FAIL",
  "item_not_ready_reason": "PROCESSING_FAILED",
  "update_fail_reason": "UNKNOWN",
  "missing_attributes": ""
}`

upload data is:
`{"ean":["4451602990613"],"title":["Durchmesser 165mm Diamant trockenes Blatt graues S\u00e4geblatt 165*20*40T 1 St\u00fcck"],"description":["<p>Beschreibung<\/p><p>Dieses Kreiss\u00e4ge blatt besteht aus hochwertigem Diamant material, hat eine hohe H\u00e4rte und ist langlebig. Scharfe Schneide f\u00fcr schnelle und reibungslose Schnitte.<\/p><p>Produkt merkmale: Dieses Kreiss\u00e4ge blatt besteht aus hochwertigem Diamant material mit hoher H\u00e4rte und ist w\u00e4hrend des Gebrauchs langlebig.<\/p><p>Dieses Kreiss\u00e4ge blatt besteht aus hochwertigem Diamant material mit hoher H\u00e4rte und ist w\u00e4hrend des Gebrauchs langlebig.<\/p><p>Dieses S\u00e4geblatt wird haupt s\u00e4chlich zum Drehen von Werkzeugen und zum Schneiden von Holz verwendet.<\/p><p>Die 40 gleichm\u00e4\u00dfig angeordneten Zacken sind sehr scharf, was einen schnellen und glatten Schnitt garantiert.<\/p><p>Scharfe Schneide, die einen schnellen und glatten Schneide effekt bietet.<\/p><p>Super hart, stabil, langlebig und effizient.<\/p><p>Hochpr\u00e4zises Schneiden, ordentlich geschnittene Streifen, glatte Abschnitte, lange Lebensdauer.<\/p><p>Spezifikation: Diamant<\/p><p>Material: Diamant<\/p><p>Au\u00dfen durchmesser: 165mm\/6,50 Zoll<\/p><p>Innen durchmesser: 20mm\/0,79 Zoll<\/p><p>Z\u00e4hne. 40T<\/p><p>Gewicht: 220g<\/p><p>Verpackung enthalten<\/p><p><\/p><p>1 x Kreiss\u00e4ge blatt<\/p><p><\/p>"],"picture":["https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/00c1029e900bf045ab6fe940431352cb.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/a4389243dc796ecd6d8d9d16e528e8dc.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/daeb224a9bef8f9c6baa75e742855d58.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/6f0b3c6749594fb66906ceb844db6240.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/f2061d9febef5661cea78615f2c0dc33.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/e8f55e5549556e1ad4d3e17b6768bdb9.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/5496532ef449be82bae7b9162c805581.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/e896eccbfb522cccd0a8468e4900fb37.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/6fe4e131db11162c3b4b8ce537d15f51.jpg","https:\/\/xtd-static.oss-cn-shenzhen.aliyuncs.com\/product\/20210702\/3ef39c0f83c68397dbf49aeb502e8447.jpg"],"category":["werkzeug"],"manufacturer":["re-Mon-rich"],"additional_attributes":[{"attribute":"list_price","value":["1234ct"]}]}`

**Comment by fengmiq** [comment]
online shop display error:Falscher Länderpräfix(Wrong country prefix), can you help me!

**Comment by NastiaNovik** [comment]
Hello @fengmiq, it looks like  ean is wrong for this product. This error means that prefix of the ean (first few digits) are not valid. Please check the correctness of the ean. You can take a look here https://www.gs1.org/standards/id-keys/company-prefix
Best regards,
Anastasia
