### ISSUE TITLE
API V2

### ISSUE THREAD

**Issue by ChrisSantiago82** [hitmeister/api-sdk-php#131]
I have received this Notification from Kaufland:
_Your version of the Kaufland.de API connection will soon no longer be supported.
01/27/2023
Your API connection to Kaufland is currently running on an outdated API version. Support for this version will shortly be discontinued. Please switch to the new Kaufland Marketplace Seller API V2 by the end of February 2023. [See the documentation](https://sellerapi.kaufland.com/)\n\nAre you using a software interface? Please contact your service provider for further information._

Is this package going to be updated to Version 2?

**Comment by ChrisSantiago82** [comment]
Looks like this package has reached it's end of life

**Comment by skrzyh** [comment]
It possible generate SDK classes by
openapi-generator-cli - php 8

java -jar openapi-generator-cli-6.4.0.jar generate   --enable-post-process-file --type-mappings enum=String -i https://sellerapi.kaufland.com/swagger.json   --additional-properties=enumUnknownDefaultCase=true,invokerPackage=KauflandAPIv2\Client --enable-post-process-file   -g php  -o kaufland-api-client-v4

or swagger-codegen-cli-3.0.41.jar php5

**Comment by ChrisSantiago82** [comment]
Yes, we just replaced this package with a own package...

**Comment by TilgalisToms** [comment]
> It possible generate SDK classes by openapi-generator-cli - php 8
> 
> java -jar openapi-generator-cli-6.4.0.jar generate --enable-post-process-file --type-mappings enum=String -i https://sellerapi.kaufland.com/swagger.json --additional-properties=enumUnknownDefaultCase=true,invokerPackage=KauflandAPIv2\Client --enable-post-process-file -g php -o kaufland-api-client-v4
> 
> or swagger-codegen-cli-3.0.41.jar php5

Hello,
Tried today and it created all the classes (via openapi-generator) but for the Enum type classes it didn't create constructors and __toString magic stubs. Is it possible to achieve this via config in openapi-generator or I have to create them myself (I am using PHP 7.4.2)?

**Comment by shaedrich** [comment]
> It possible generate SDK classes by openapi-generator-cli - php 8
> 
> java -jar openapi-generator-cli-6.4.0.jar generate --enable-post-process-file --type-mappings enum=String -i https://sellerapi.kaufland.com/swagger.json --additional-properties=enumUnknownDefaultCase=true,invokerPackage=KauflandAPIv2\Client --enable-post-process-file -g php -o kaufland-api-client-v4
> 
> or swagger-codegen-cli-3.0.41.jar php5

Does this result in only the changes between v1 and v2 or does the generator create a different structure? If the former applies, would you mind sharing your result as a PR? Even though, it is not merged quickly, one could install the dependency from the respective branch for the time being.
