### ISSUE TITLE
order_units/seller response strips leading 0 from postcode

### ISSUE THREAD

**Issue by neonics** [hitmeister/api-sdk-php#15]
Hello,

My apologies: this issue concerns the server-side Hitmeister API, not this library, but I could not find anywhere else to report it. Please let me know if I should report this elsewhere.

When a customer has a postcode with a leading zero, such as `09117`  the `order_units/seller` API call response returns `9117`. Here's a partial `print_r` of the response:

```
Array
(
    [0] => stdClass Object
        (
            [id_order_unit] => 3145678........
            [id_order] => MFT....
            .....

            [billing_address] => stdClass Object
                (    
                    ....
                    [postcode] => 9117
                    ....
                    [country] => DE
                )

            [shipping_address] => stdClass Object
                (
                    ....
                    [postcode] => 9117
                    ....
                    [country] => DE
                )

```

I double checked that the invoice contains the proper postcode (it does).
We can work around this but I thought I'd mention the bug.

Thanks,
  Kenney

**Comment by aazon** [comment]
Hello Kenney, 

Thanks for your report. I'll take a look asap and let you know immediately.

Alex.

**Comment by aazon** [comment]
Kenney,

I found a bug in our API and have committed a bugfix. 
It will go live during next deploy - on Monday, July 25th. I'll add a message here after we deploy.
Thanks again for you report. 

Alex.

**Comment by neonics** [comment]
Alex,

You're welcome, and thank you for picking it up so quickly!

Kenney.

**Comment by aazon** [comment]
Hello Kenney,

This bugfix is live. From now on postcode field is string and thus may start with zero.

Alex.

**Comment by neonics** [comment]
Hi Alex,

Verified! Thanks a lot!
