### ISSUE TITLE
generate_sample_data orders

### ISSUE THREAD

**Issue by staabm** [hitmeister/api-sdk-php#2]
the old api had a GET parameter which was used to generate sample data, namely `generate_sample_data`.

does the new api also has the ability?

alternatively, do you have a sandbox on which we can test our code against?

**Comment by aazon** [comment]
Right now API does not have neither sample data nor sandbox mode.

Sorry for that, I hope one day we'll introduce some tools for developers.

As for today all `GET` requests are "safe" and will never change the real data, thus one can test code against them without any fear.
