### ISSUE TITLE
Endpoint Documnetation OrderUnit.Status Incomplete

### ISSUE THREAD

**Issue by michael-herwig** [hitmeister/api-sdk-php#35]
Hi there,

according to you endpoint documentation the order unit status is one of the following values `['need_to_be_sent' or 'sent' or 'received' or 'cancelled' or 'sent_and_autopaid' or 'returned']`. However the API also returns `'returned_paid'`.

Regards
Michael

**Comment by aazon** [comment]
Hello Michael,

Thanks for your report. This is definitely a lag in the documentation. We will fix it ASAP in the next API release.

Best Regards,
Alex

**Comment by aazon** [comment]
Hello Michael,

We updated documentation on the API webpage.

Thanks for your report and please feel free to contact us in case of any issues.

Best Regards,
Alex
