### ISSUE TITLE
Method /product-data/{ean} returns no result

### ISSUE THREAD

**Issue by TilgalisToms** [hitmeister/api-sdk-php#58]
When trying to check product data with following code:

```
use Hitmeister\Component\Api\ClientBuilder;

$api_instance = ClientBuilder::create()
				->setClientKey($settings['client_key'])
				->setClientSecret($settings['secret_key'])
				->build();
$productData = $api_instance->productData();
$data = $productData->get($ean);
```

I get null as result. When executing same method via sandbox or standalone cURL request correct result is returned.

**Comment by johnholiver** [comment]
Thanks for your report, we'll investigate.

**Comment by TilgalisToms** [comment]
Hello,
Client key: 311e6889608d90b9d54270a5ae11fa76
EAN: 0810354022210

**Comment by FFluche** [comment]
Hello,
we investigated in that issue and could reproduce it.
The only possibility to get a NULL result from our SDK when your EAN is not connected to any of your products. Perhaps you have a typo in your EAN.

**Comment by sleipi** [comment]
Same issues here. And also a PR https://github.com/hitmeister/api-sdk-php/pull/92 which solve the issue
