### ISSUE TITLE
Is a product_feed downloaded multiple times?

### ISSUE THREAD

**Issue by christopherglander** [hitmeister/api-sdk-php#8]
Hi, 

when I post an uri of my product csv to Hitmeister, do they keep an eye on my remote file or do they only look one time and then never again at my file? Do they trace my CRUD operations described in my remote file?

Regards

**Comment by mansurs** [comment]
Hi,
we download the file only one time into our system and read it then. There can't be any CRUD operations in you file. We just replace the data which you send to us in our system. Have a look at https://www.hitmeister.de/api/v1/?page=product-data#uploading-and-updating-items and https://www.hitmeister.de/api/v1/?page=product-data-files
Regards

**Comment by christopherglander** [comment]
Hi,

well, the REST endpoint documentation is and was a bit confusing. Have a look at the description of the "POST /import-files/" endpoint. The description tells me that a file is downloaded several times a day.

Quote: 
> Implementation Notes
> Saves a URL where a new import file is located. The file located at the URL _will be downloaded several times per day_ and the contents imported.

I am a bit confused, so could you please explain it to me furthermore? 

Regards

**Comment by mansurs** [comment]
Sorry, but the documentation is wrong. We will fix it as soon as possible.
The file is downloaded only once.

Regards and thank you for the finding!
