### ISSUE TITLE
Shipping without tracking

### ISSUE THREAD

**Issue by DominicWatts** [hitmeister/api-sdk-php#82]
On frontend you can ship order items without tracking. Via API this appears to be impossible.

The work around I found was to provide courier and a space character as tracking code. The API returns true so this appears acceptable.

Providing null value as tracking omits parameter from request body and therefore fails validation.

**Comment by aazon** [comment]
Hello Dominic,

Thanks for your request.

The following combination will be valid in case there is no tracking information:

```
{
  "carrier_code": "Other",
  "tracking_number": ""
}
```

Alex.

**Comment by DominicWatts** [comment]
Yes and how do you send that using the SDK?

Only thing worked for me was

```
...->send(1234567890, 'Other', ' ')
```

Other combinations failed validation.

If you send a null or false value as a param you don't get the above structure. Or at least it didnt do for me.

https://github.com/hitmeister/api-sdk-php/blob/13821631bdc50adfc2c4f298d025cf5fc1294fb2/src/Namespaces/OrderUnitsNamespace.php#L129-L134

Is it not because of this?

```
		if (null !== $carrierCode) {
			$data->carrier_code = $carrierCode;
		}
		if (null !== $trackingNumber) {
			$data->tracking_number = $trackingNumber;
		}
```

**Comment by mansurs** [comment]
Yes, I think you can also remove the space and just put an empty string:
`...->send(1234567890, 'Other', '')`

**Comment by DominicWatts** [comment]
Perhaps I'm not making myself clear

When you do that - so empty string you get an error

```
Fatal error: Uncaught exception 'Hitmeister\Component\Api\Exceptions\BadRequestException' with message 'Required field body.tracking_number is missing' in /home/x/admin/vendor/hitmeister/api-sdk/src/Middleware.php:94 Stack trace: 
#0 /home/x/admin/vendor/react/promise/src/FulfilledPromise.php(25): Hitmeister\Component\Api\Middleware::Hitmeister\Component\Api\{closure}(Array) 
#1 /home/x/admin/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) 
#2 /home/x/admin/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) 
#3 /home/x/admin/vendor/hitmeister/api-sdk/src/Middleware.php(112): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) 
#4 /home/x/admin/vendor/hitmeister/api-sdk/src/Transport/Transport.php(57): Hitmeister\Component\Api\Middleware::Hitmeister\Component\Api\{closure}(Array) in /home/x/admin/vendor/hitmeister/api-sdk/src/Middleware.php on line 94
```

**Comment by mansurs** [comment]
I see, thanks. There seems to be a misconception on our side. Basically we wanted to make carrier/tracking number optional, because we have a new Endpoint "shipments", where you can add tracking numbers after sending an order-unit. Seems like it was not completely fulfilled. We need to fix that.

As a workaround you may use your suggestion with "Other" and " ".
