### ISSUE TITLE
Passing "additional_attributes" to productData()->update produces api error

### ISSUE THREAD

**Issue by loertel** [hitmeister/api-sdk-php#85]
Creating a new Product with productData()->update or upsert Method produces an api error response from real endpoint: "Field body.additional_attributes should be an object"

**Comment by NastiaNovik** [comment]
That is correct, productData()->update expects a JSON object containing the product data. Could you please send an example of your request?

**Comment by mainIine** [comment]
I have the same problem but in the upsert().

Because all data of the product is passed together with the additional_attributes I can not reproduce the error.

**Comment by NastiaNovik** [comment]
@dsiekiera do you have this problem every time? Could you please send the example of your request? (data can be fake)

**Comment by mainIine** [comment]
Sure. Here is a part of it:

```php
.
.

$_json = [
	'ean' => $_data['ean'],
	'title' => $_data['attributes']['name'],
	'category' => $_data['attributes']['categoryName'],
	'description' => preg_replace('/\s+/S', " ", $_data['attributes']['description']),
	'mpn' => empty($_data['suppliernumber'],
	'Gewicht' => $_data['weight'],
	'condition' => 'new',
	'amount' => $_data['available_stock'],
	'location' => 'DE',
	'listing_price' => number_format($_data['attributes']['price'], 2, '', ''),
];

if(file_exists('media/articles/thumb/'.$_data['id'].'-1.jpeg')){
	$_json['picture'] = 'https://domain.com/media/articles/original/'.$_data['id'].'-1.jpeg';
}


// prüfen ob es das Produkt bereits gibt
$_result = $api->items()->findByEan($_data['ean']);


// die EAN gibt es noch nicht
if(empty($_result)){
	
	// json umwandeln
	$_arrayJSON = [];
	foreach($_json as $key => $value){
		$_arrayJSON[$key] = [$value];
	}
	
	// falls es attribute gibt, mit anhängen
	if(!empty($_data['attributes']['category_attributes'])){
		$ca = unserialize($_data['attributes']['category_attributes']);
		
		$_attributes = [];
		
		foreach($ca as $a)
		{
			if(empty($a['value'])){
				continue;
			}
			
			$_attributes[] = [
				$a['name'] => [$a['value']]
			];
		}
		
		if(!empty($_attributes)){
			$_arrayJSON['additional_attributes'] = $_attributes;
		}
	}
	
	
	// https://www.real.de/api/v1/?page=product-data
	// und weg damit (Produktdaten)
	
	try {
		$_result = $api->productData()->upsert($_data['ean'], \Hitmeister\Component\Api\Transfers\ProductDataTransfer::make($_arrayJSON));
		
		echo '<pre>';
		print_r($_result);
		echo '</pre>';
		
	} catch (Exception $e) {
		
		echo 'Fehler: ',  $e->getMessage(), "\n";
		
	}
	exit;
	
	.
	.
	.
```

```$_json``` is completly filled.

Without the ```additional_attributes``` it works like charme. But with, i always a got the error above.

I hope this is enough?

**Comment by mainIine** [comment]
Any findings? For example, the API cannot really be used effectively.

**Comment by NastiaNovik** [comment]
Could you please try to change your structure of your request a bit and tell me if that works? 
`"additional_attributes": [
    {
      "attribute":  "$a['name'] ,
      "value": [
          "$a['value']"
      ]
    }` 
So that the $a['name']  will be a value of "attribute" and $a['value'] will go to value of "value". And each new additional attribute should follow that structure.

**Comment by mainIine** [comment]
@NastiaNovik 

I have changed the structure. It no longer throws a mistake, but nothing comes back.

The answer from 
```php
$api->productData()->upsert($_data['ean'], \Hitmeister\Component\Api\Transfers\ProductDataTransfer::make($_arrayJSON));
```
is only "1".

I don't see any new entry at https://www.real.de/seller/ either.

**Comment by NastiaNovik** [comment]
@dsiekiera  could you please send me more info about your shop? Like the name of your shop. So I can see logs.
You can send it to my work email anastasiia.novik@real-digital.de
