### ISSUE TITLE
Question regarding giving/receiving date/times from the API and their timezones

### ISSUE THREAD

**Issue by mylemans** [hitmeister/api-sdk-php#89]
See for example:

https://github.com/hitmeister/api-sdk-php/blob/990c68766fe79aa56cdb304d4ec9bf6d21d9dbee/tests/Namespaces/ReturnUnitsNamespaceTest.php#L33

As far I see, this means that because it uses date('Y-m-d H:i:s', ...) it'll use the configured local timezone that may or may not be UTC.

I think that the unit tests are ran with the time zone configured as UTC, but I cannot find documentation on real.de end stating that the UTC time should be taken (and not, for example, 'Europe/Berlin' time). 

Can anyone confirm that what real.de expects is a UTC date/time and not a German one?

In addition, once this is figured out, it might be best to mention this in the README.md file (that they should make sure their timezone matches what real.de expects)

**Comment by NastiaNovik** [comment]
Thank you for your comment.
We save data in German Time Zone. 

You are right, we might need to mention this in the documentation.

**Comment by mylemans** [comment]
Shouldn't it be better to alter the tests so the 'time zone' while testing isn't UTC, but one matching German time?

**Comment by NastiaNovik** [comment]
We will consider this, thanks.
