### ISSUE TITLE
how upsert a new item with new ean code?

### ISSUE THREAD

**Issue by biohardware** [hitmeister/api-sdk-php#90]
hi, i try upload a new item with new ean, this ean not exist on real.de database!

my code:

`  

 $namespace = new ProductDataNamespace($client->getTransport());
 $pd = $client->productData($client->getTransport());

$data = [
            "ean" => [$newEan],
            "category" => ['angelruten'],
            "title" => [$neve],
            "picture" => ["https://racvarosihorgaszbolt.hu/public/upload/termek_kepek/bot/pergeto/nevis-ryder-baitcast-240m-20-50gr-horgaszbot-1691-240.jpg","http://pds-pictures-seller.s3.amazonaws.com/5998214360810/34274624/383fef385c40dc73e8c9185c52fa5985.jpg"],
            "description"=> ["this is description"],
            "mpn" => [],
            "short_description" => [],
            "list_price" => [],
            "manufacturer"=> []
        ];
       $try = $namespace->upsert($newEan, ProductDataTransfer::make($data));
print_r($try);
`
it upload a new product but its not valid and havent image and description and category,
its just have title and ean code!

please help thanks

**Comment by NastiaNovik** [comment]
hi @biohardware, could you please send new EAN?

**Comment by mansurs** [comment]
Seem like not an issue -> close
